### PR TITLE
Initial implementation for copying Fedora PASS data into a deposit service data model.

### PR DESCRIPTION
**Pull request by Trumbore**
This PR is only supposed to be for the two commits on 4/16, 7087e60 and 87c0a4b, which implement functionality (as opposed to the other commits listed here, which involve module renaming and are already included in a separate PR).

Karen, I have included you because the PassJsonFedoraAdapter class makes substantial use of the Fedora Client project.  PassJsonFedoraAdapterTest demonstrates round-tripping such data from a JSON file up to a Fedora server and back.  You might also look at the ModelBuilder class, which walks through a tree of PassEntity to copy values to the deposit data model.

Thanks!

   Ben

### CODE REVIEW

**Comment by Trumbore** [comment]
I should note that the classes and tests that retrieve data from Fedora will currently only work using the Fedora server that is available from the java-fedora-client project, which has an up-to-date context.  Because of this, I did not run the nihms-integration tests before making this submission, though I now realize that with some work an updated Fedora server could be run on a separate system from the docker container that is needed for those tests.

**Comment by emetsger** [comment]
@Trumbore after merging #38, it appears there are some conflicts.  I think your best best is to rebase this PR against master.  Hopefully the pesky merge commit 50a4f04 doesn't appear in the PR; I don't think it will need to be there.

**Comment by emetsger** [comment]
@Trumbore yes, so my feedback at this juncture is that integration tests need to run as integration tests in travis against Fedora in pass-docker.  Let's get together and figure out what the next steps are.

**Comment by emetsger** [comment]
Merged into master 25a3e81.

**Comment by emetsger** [comment]
@Trumbore I had to some slicing and dicing with this PR to get it to rebase cleanly against master.  I merged this PR locally on my machine and pushed to `master` instead of using the "big green button" here in the GH UI.  (Just FYI).

Anyway, should be all merged up.

**Pull request closed without merging**
